# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/a21s-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter gta4xlwifi gta4xl,$(TARGET_DEVICE)),)

endif
